apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  cluster:
    chartRepository: http://bucketrepo.jx.svc.cluster.local/bucketrepo/charts
    clusterName: minikube
    devEnvApprovers:
    - WillLin-Advantech
    environmentGitOwner: WillLin-Advantech
    gitKind: github
    gitName: github
    gitServer: https://github.com/WillLin-Advantech/jx3-kubernetes.git
    provider: kubernetes
    registry: eap-cr.advantech.com.tw/test
  environments:
  # - key: dev
  # - key: staging
  # - key: production
  - key: chore/20250627-test-email-notification
  ingress:
    domain: 192.168.49.2
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: eap-cr.advantech.com.tw/test/
  secretStorage: local
  vault: {}
  webhook: lighthouse
